In [7]:
import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit,total_sales
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [8]:
import pandas as pd

df = pd.read_csv("cleaned_superstore.csv")
df.head()

,row_id,order_id,order_date,ship_date,ship_mode,customer_id,customer_name,segment,country,city,...,region,product_id,category,sub-category,product_name,sales,quantity,discount,profit,total_sales
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [9]:
import sqlite3

conn = sqlite3.connect("superstore.db")

df.to_sql("sales", conn, if_exists="replace", index=False)

9994

In [11]:
pd.read_sql_query("""
SELECT
    customer_name,
    ROUND(SUM(total_sales), 2) AS total_revenue
FROM sales
GROUP BY customer_name
ORDER BY total_revenue DESC
LIMIT 10;
""", conn)

     customer_name  total_revenue
0      Sean Miller      146749.77
1    Adrian Barton      143857.71
2     Tamara Chand       92602.57
3     Becky Martin       88175.27
4      Joseph Holt       80520.04
5     Ken Lonsdale       74912.31
6        Greg Tran       73016.05
7    Maria Etezadi       71594.30
8     Bill Shonely       71586.33
9  Patrick O'Brill       69297.41

In [12]:
pd.read_sql_query("""
SELECT
    customer_name,
    COUNT(DISTINCT order_id) AS order_count
FROM sales
GROUP BY customer_name
ORDER BY order_count DESC
LIMIT 10;
""", conn)

         customer_name  order_count
0           Emily Phan           17
1     Zuschuss Carroll           13
2        Sally Hughsby           13
3      Patrick Gardner           13
4         Noel Staavos           13
5           Joel Eaton           13
6        Erin Ashbrook           13
7  Chloris Kastensmidt           13
8       Suzanne McNair           12
9        Sanjit Jacobs           12

In [13]:
pd.read_sql_query("""
SELECT
    customer_name,
    COUNT(DISTINCT order_id) AS order_count
FROM sales
GROUP BY customer_name
HAVING COUNT(DISTINCT order_id) > 1
ORDER BY order_count DESC;
""", conn)

        customer_name  order_count
0          Emily Phan           17
1    Zuschuss Carroll           13
2       Sally Hughsby           13
3     Patrick Gardner           13
4        Noel Staavos           13
..                ...          ...
776     Bryan Spruell            2
777    Brendan Dodson            2
778       Brad Thomas            2
779     Bobby Odegard            2
780      Adrian Shami            2

[781 rows x 2 columns]

In [14]:
pd.read_sql_query("""
SELECT
    customer_name,
    ROUND(SUM(profit), 2) AS total_profit
FROM sales
GROUP BY customer_name
ORDER BY total_profit DESC
LIMIT 10;
""", conn)

          customer_name  total_profit
0          Tamara Chand       8981.32
1          Raymond Buch       6976.10
2          Sanjit Chand       5757.41
3          Hunter Lopez       5622.43
4         Adrian Barton       5444.81
5          Tom Ashbrook       4703.79
6  Christopher Martinez       3899.89
7         Keith Dawkins       3038.63
8           Andy Reiter       2884.62
9         Daniel Raglin       2869.08

In [15]:
pd.read_sql_query("""
SELECT
    customer_name,
    ROUND(AVG(total_sales), 2) AS avg_order_value
FROM sales
GROUP BY customer_name
ORDER BY avg_order_value DESC
LIMIT 10;
""", conn)

       customer_name  avg_order_value
0        Sean Miller          9783.32
1    Kelly Collister          9573.71
2   Mitch Willingham          8875.12
3       Bill Shonely          7954.04
4       Tamara Chand          7716.88
5  Stefanie Holloman          7318.40
6      Adrian Barton          7192.89
7       Tom Ashbrook          6667.17
8     Grant Thornton          6140.39
9        Joseph Holt          5751.43

In [16]:
pd.read_sql_query("""
SELECT
    segment,
    ROUND(SUM(total_sales), 2) AS total_revenue,
    ROUND(SUM(profit), 2) AS total_profit,
    COUNT(DISTINCT order_id) AS total_orders
FROM sales
GROUP BY segment
ORDER BY total_revenue DESC;
""", conn)

       segment  total_revenue  total_profit  total_orders
0     Consumer     5819347.40     134119.21          2586
1    Corporate     3516107.67      91979.13          1514
2  Home Office     2152607.00      60298.68           909

In [17]:
pd.read_sql_query("""
SELECT
    segment,
    ROUND(SUM(profit), 2) AS total_profit,
    ROUND(SUM(total_sales), 2) AS total_revenue,
    ROUND((SUM(profit) / SUM(total_sales)) * 100, 2) AS profit_margin_percentage
FROM sales
GROUP BY segment
ORDER BY profit_margin_percentage DESC;
""", conn)

       segment  total_profit  total_revenue  profit_margin_percentage
0  Home Office      60298.68     2152607.00                      2.80
1    Corporate      91979.13     3516107.67                      2.62
2     Consumer     134119.21     5819347.40                      2.30

In [18]:
pd.read_sql_query("""
SELECT
    customer_name,
    ROUND(SUM(total_sales), 2) AS total_revenue,
    ROUND(SUM(profit), 2) AS total_profit
FROM sales
GROUP BY customer_name
HAVING SUM(profit) < 0
ORDER BY total_profit ASC
LIMIT 10;
""", conn)

      customer_name  total_revenue  total_profit
0     Cindy Stewart       26668.83      -6626.39
1    Grant Thornton       36842.33      -4108.66
2       Luke Foster       27578.11      -3583.98
3    Sharelle Roach       14772.98      -3333.91
4     Henry Goldwyn       16023.13      -2797.96
5       Nathan Cano       10929.03      -2204.81
6      Sean Braxton       41458.72      -2082.75
7       Sean Miller      146749.77      -1980.74
8    Christine Phan       27833.14      -1850.30
9  Natalie Fritzler       35217.77      -1695.97